# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b85595cc3f47f524f9bcfb5d0a60bc1d"
name = "cartbundle-app"
application_url = "https://cartbundle.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [ "https://cartbundle.app/api/auth" ]

[build]
automatically_update_urls_on_dev = true
