# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c812c9caf9208233e1ad77170a906762"
name = "CartBundle"
application_url = "https://cartbundle-ed4680083865.herokuapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products,read_products,read_discounts"

[auth]
redirect_urls = [ "https://cartbundle-ed4680083865.herokuapp.com/api/auth" ]

[app_proxy]
url = "https://cartbundle-ed4680083865.herokuapp.com/cart-drawer-settings"
subpath = "cart-drawer-settings"
prefix = "apps"
