# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c812c9caf9208233e1ad77170a906762"
name = "CartBundle"
application_url = "https://cartbundle-ed4680083865.herokuapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
# Use a real, current API version
api_version = "2025-10"

  # Handled by: /app/routes/webhooks.tsx
  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products, write_products, read_discounts, write_discounts"

[auth]
redirect_urls = [
  "https://cartbundle-ed4680083865.herokuapp.com/api/auth/callback"
]

[app_proxy]
url = "https://cartbundle-ed4680083865.herokuapp.com/cart-drawer-settings"
subpath = "cart-drawer-settings"
prefix = "apps"