# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "faa64ef41d6694c2e76d3fa600323b06"
name = "carting bundle II"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_products,write_discounts,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/cart-drawer-settings"
subpath = "cart-drawer-settings"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
